---
- name: install nginx
  apt: name=nginx state=latest force=yes

- name: create vhost
  template: src=templates/nginx.conf dest=/etc/nginx/sites-available/devel.conf

- name: available vhost
  file: src=/etc/nginx/sites-available/devel.conf dest=/etc/nginx/sites-enabled/devel.conf state=link

- name: nginx must start after boot
  service: name=nginx enabled=yes

- name: nginx up
  service: name=nginx state=restarted